### ISSUE TITLE
Please add annotation to KafkaAccess CRD for Service Binding Operator discoverability

### ISSUE THREAD

**Issue by paul-snively** [strimzi/kafka-access-operator#12]
Hi folks!

First of all, thanks for developing this.

In the course of attempting to use it, I discovered that the `KafkaAccess` I created isn't discoverable by the Service Binding Operator, by which I mean the resource did not appear in the list of "bindable services" shown by [odo](https://odo.dev/). The reason for this is the lack of any appropriate [metadata to expose binding information](https://docs.openshift.com/container-platform/4.9/applications/connecting_applications_to_services/exposing-binding-data-from-a-service.html#declaring-binding-data-through-crd-or-cr-annotations) on the CRD.

It seems I can add the annotation to the `CustomResource` rather than having it on the `CustomResourceDefinition`, so I'm about to try that. But it would make the operator even more attractive, IMO, if it would simply do this "out of the box."

**Comment by scholzj** [comment]
CC @katheris

**Comment by paul-snively** [comment]
*Update*: Unfortunately, annotating the `CustomResource` itself does not make the service discoverable by `odo list services -A` as I had hoped. So it seems adding the annotation(s) to the CRD is our only recourse.

**Comment by katheris** [comment]
Hi @paul-snively, thanks for raising this. It looks like from the spec it is recommended to have a label in the CRD that is `servicebinding.io/provisioned-service: "true"` Would you be able to update your KafkaAccess CRD to add that label and verify if that makes it discoverable? If that works then I will look to add this annotation to the KafkaAccess CRD as part of the build.

**Comment by paul-snively** [comment]
@katheris, thanks for looking into this!

Unfortunately, given:

`paulsnively@Paul-Snively's-MacBook-Pro:~/moonraker/moonraker-notifications|main⚡ ⇒  kubectl describe -n strimzi-access-operator crd/kafkaaccesses.access.strimzi.io

```yaml
Name:         kafkaaccesses.access.strimzi.io
Namespace:    
Labels:       servicebinding.io/provisioned-service=true
Annotations:  <none>
API Version:  apiextensions.k8s.io/v1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2022-10-03T13:24:59Z
  Generation:          1
  Managed Fields:
    API Version:  apiextensions.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:kind:
          f:listKind:
          f:plural:
          f:shortNames:
          f:singular:
        f:conditions:
          k:{"type":"Established"}:
            .:
            f:lastTransitionTime:
            f:message:
            f:reason:
            f:status:
            f:type:
          k:{"type":"NamesAccepted"}:
            .:
            f:lastTransitionTime:
            f:message:
            f:reason:
            f:status:
            f:type:
    Manager:      Go-http-client
    Operation:    Update
    Subresource:  status
    Time:         2022-10-03T13:24:59Z
    API Version:  apiextensions.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:servicebinding.io/provisioned-service:
      f:spec:
        f:conversion:
          .:
          f:strategy:
        f:group:
        f:names:
          f:kind:
          f:listKind:
          f:plural:
          f:shortNames:
          f:singular:
        f:scope:
        f:versions:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2022-10-03T13:24:59Z
  Resource Version:  167578
  UID:               3aff9e86-1f32-4588-85b9-968e64c6a109
Spec:
  Conversion:
    Strategy:  None
  Group:       access.strimzi.io
  Names:
    Kind:       KafkaAccess
    List Kind:  KafkaAccessList
    Plural:     kafkaaccesses
    Short Names:
      ka
    Singular:  kafkaaccess
  Scope:       Namespaced
  Versions:
    Name:  v1alpha1
    Schema:
      openAPIV3Schema:
        Properties:
          Spec:
            Properties:
              Kafka:
                Properties:
                  Listener:
                    Type:  string
                  Name:
                    Type:  string
                  Namespace:
                    Type:  string
                Required:
                  name
                Type:  object
              User:
                Properties:
                  API Group:
                    Type:  string
                  Kind:
                    Type:  string
                  Name:
                    Type:  string
                  Namespace:
                    Type:  string
                Required:
                  apiGroup
                  kind
                  name
                Type:  object
            Required:
              kafka
            Type:  object
          Status:
            Properties:
              Binding:
                Properties:
                  Name:
                    Type:  string
                Type:      object
              Observed Generation:
                Type:  integer
            Type:      object
        Type:          object
    Served:            true
    Storage:           true
    Subresources:
      Status:
Status:
  Accepted Names:
    Kind:       KafkaAccess
    List Kind:  KafkaAccessList
    Plural:     kafkaaccesses
    Short Names:
      ka
    Singular:  kafkaaccess
  Conditions:
    Last Transition Time:  2022-10-03T13:24:59Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  2022-10-03T13:24:59Z
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1alpha1
Events:  <none>
```
I still get:

```
paulsnively@Paul-Snively's-MacBook-Pro:~/moonraker/moonraker-notifications|main⚡ ⇒  odo list services -A                       ✓  Listing bindable services from all namespaces [68ms]

 NAME                                                          NAMESPACE 
 postgresql/PostgresCluster.postgres-operator.crunchydata.com  moonraker 
```

It seems the annotations described in the first link, which are also used by the Crunchy Data Postgres operator, are necessary for the Service Binding Operator to discover the "bindability" of an operator. I suppose it makes some sense: the annotations specify not only that the service is bindable (true or false), but specify an expression providing the resource the service provides for binding—typically a secret.

Thanks again!
